* Merge Debian GNU/Linux changes between 2.02~beta2-9 and 2.02~beta2-21. * Change versioning - Amazon S3 can't handle '+'. * Update debian/patches patches (to accommodate GIT version).

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -299,6 +299,14 @@ running_in_container()
   type running-in-container >/dev/null 2>&1 && running-in-container >/dev/null
 }
 
+run_grub_install()
+{
+    if ! grub-install $@ ; then
+        echo "Failed: grub-install $@" >&2
+        echo "WARNING: Bootloader is not properly installed, system may not be bootable" >&2
+    fi
+}
+
 case "$1" in
   configure)
     . /usr/share/debconf/confmodule
@@ -411,6 +419,7 @@ case "$1" in
             # No || true here; it's vital that the user sees this, and it's
             # better to throw an error than to do the wrong thing.
             db_subst grub-pc/mixed_legacy_and_grub2 DISKS "$grub2_disks"
+            db_fset grub-pc/mixed_legacy_and_grub2 seen false
             db_input critical grub-pc/mixed_legacy_and_grub2
             db_go
             db_get grub-pc/mixed_legacy_and_grub2
@@ -463,6 +472,7 @@ case "$1" in
              test -e /boot/grub/@FIRST_CPU_PLATFORM@/core.img || \
              test "$UPGRADE_FROM_GRUB_LEGACY" || test "$wubi_device"; then
           question=grub-pc/install_devices
+          priority=high
           device_map="$(grub-mkdevicemap -m - | grep -v '^(fd[0-9]\+)' || true)"
           devices="$(echo "$device_map" | cut -f2)"
           if dpkg --compare-versions "$2" lt 1.98+20100702-1 && \
@@ -532,6 +542,7 @@ case "$1" in
             done
             if [ "$valid" = 0 ]; then
               question=grub-pc/install_devices_disks_changed
+              priority=critical
               db_set "$question" "$RET"
               db_fset "$question" seen false
               db_fset grub-pc/install_devices_empty seen false
@@ -578,7 +589,7 @@ case "$1" in
             done
             db_subst "$question" RAW_CHOICES "$ids"
             db_subst "$question" CHOICES "$descriptions"
-            db_input high "$question" || true
+            db_input "$priority" "$question" || true
             db_go
             db_get "$question"
             failed_devices=
@@ -660,13 +671,12 @@ case "$1" in
         fi
 
         # /boot/grub/ has more chances of being accessible by GRUB
-        if test -e /boot/grub/grub.cfg ; then
-          for i in /usr/share/grub/unicode.pf2 ; do
-            if test -e $i ; then
-              cp $i /boot/grub/
-            fi
-          done
-        fi
+        for i in /usr/share/grub/unicode.pf2 ; do
+          if test -e $i ; then
+            mkdir -p /boot/grub
+            cp $i /boot/grub/
+          fi
+        done
 
         if [ "$fix_mixed_system" ]; then
           # These never contain any valuable information, and they aren't
@@ -693,7 +703,11 @@ case "$1" in
             grub-efi-arm)   target=arm-efi ;;
             grub-efi-arm64) target=arm64-efi ;;
           esac
-          grub-install --target="$target"
+          db_get grub2/force_efi_extra_removable
+          if [ "$RET" = true ]; then
+            FORCE_EXTRA_REMOVABLE="--force-extra-removable"
+          fi
+          run_grub_install --target="$target" "$FORCE_EXTRA_REMOVABLE"
         fi
 
         # /boot/grub/ has more chances of being accessible by GRUB
@@ -708,13 +722,27 @@ case "$1" in
       grub-ieee1275)
         case $(dpkg --print-architecture) in
           ppc64el)
-            grub-install --target=powerpc-ieee1275
+            # Output may be empty; if so, just update the core image but
+            # don't install it to any PReP partition.
+            prep_bootdev="$(/usr/lib/grub/powerpc-ieee1275/prep-bootdev)"
+            run_grub_install --target=powerpc-ieee1275 $prep_bootdev
           ;;
         esac
       ;;
 
       grub-yeeloong)
-        grub-install --target=mipsel-loongson
+        run_grub_install --target=mipsel-loongson
+      ;;
+
+      grub-xen)
+        # Install for x86_64 regardless of arch, since a 32-bit userspace can still boot with a 64-bit kernel.
+        mkdir -p /boot/xen
+        run_grub_install --target=x86_64-xen
+        case $(dpkg --print-architecture) in
+          i386)
+            run_grub_install --target=i386-xen
+          ;;
+        esac
       ;;
     esac
 
